Add support for dual mono setups (AVPro)
llealloo/audiolink pull request #318
Opened 2024-07-25 06:34 UTC by fundale

Optional support for dual mono audio

2024-07-25 08:38 UTC, float3 requested changes

2024-07-25 08:38 UTC, float3 commented on Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
> +                    if (VRC.SDKBase.Utilities.IsValid(optionalRightAudioSource))
issue (blocking): any calls to VRC namespace stuff should be wrapped with `#if UDONSHARP` or `#if VRC_SDK_VRCSDK3` depending on if that codepath should be taken in Avatar Projects, in this case I believe it should be `UDONSHARP`

2024-07-25 08:38 UTC, float3 commented on Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
> +                if (VRC.SDKBase.Utilities.IsValid(optionalRightAudioSource))        // check if dual mono is present
issue (blocking): any calls to VRC namespace stuff should be wrapped with `#if UDONSHARP` or `#if VRC_SDK_VRCSDK3` depending on if that codepath should be taken in Avatar Projects, in this case I believe it should be `UDONSHARP`

2024-07-25 15:54 UTC, float3 approved these changes
lgtm

2024-08-09 18:58 UTC, pema99 commented
The change looks fine to me, but could you enlighten me a bit on how this should be used? It looks like it will just always pull the data from the newly added audio source field if it isn't null. Isn't this for switching between 2 audio sources? How do you actually switch?

2024-08-09 19:29 UTC, fundale commented
> @fundale The change looks fine to me, but could you enlighten me a bit on how this should be used? It looks like it will just always pull the data from the newly added audio source field if it isn't null. Isn't this for switching between 2 audio sources? How do you actually switch?

This isn't for switching between two separate videoplayers or audiosources,
it's intention is to provide a way for video players using separate left and right speakers to function better.
Like when using AVPro through ProTV, VideoTXL, USharpVideo, etc.

As some audio may be stereo encoded with temporary mono right audio, that currently would not be captured when setup with AVPro unless using Stereo Mix

2024-08-09 19:46 UTC, pema99 commented
So how exactly is a user intended to use this? What do they plug into the optional right source slot? The only difference I see in code is the channel they sample from, and only one is used at any given time

2024-08-09 20:01 UTC, fundale commented
> So how exactly is a user intended to use this? What do they plug into the optional right source slot? The only difference I see in code is the channel they sample from, and only one is used at any given time

If they're using a 2D Stereo mix source nothing changes with how they use it,

But for users using AVPro with dual mono they would have the left audio source remain in the current Audio Source slot, with the right audio source going into the Optional Right Audio Source.

Some video players already automate connecting to AudioLink so they may be able to auto configure it accordingly for users

It should still sample from left and right at the same time and combine them the same way AudioLink already does

2024-08-09 20:15 UTC, pema99 commented
Oh, I was misreading the diff. It looks fine to me with your explanation.

2024-08-09 20:15 UTC, pema99 approved these changes

2024-08-09 20:15 UTC, merged